name:                decidable
version:             0.1.0.0
github:              "mstksg/decidable"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Combinators for manipulating dependently-typed predicates.
category:            Dependent Types

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/decidable#readme>

ghc-options:
- -Wall
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- singletons >= 2.4

library:
  source-dirs: src
